parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FrontBundle\:
        resource: '../../src/FrontBundle/*'
        exclude: '../../src/FrontBundle/{Entity,Repository,Tests}'

    FrontBundle\Controller\:
        resource: '../../src/FrontBundle/Controller'
        public: true
        tags: ['controller.service_arguments']